log:
  format: text # text / json
  level: debug # debug / info / warn / error
  caller: true
google:
  endpoints:
    token: https://oauth2.googleapis.com/token
  oauth:
    client-id: <oauth_client_id>
    client-secret: <oauth_client_secret>
